import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { TodoList } from "../components/TodoList";
import { TitleForm } from "../components/TitleForm";
import { SearchForm } from "../components/SearchForm";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TitleForm />
      <SearchForm />
      <TodoList />
    </div>
  );
};

export default Home;
